# Generated by Django 5.1.3 on 2024-11-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiView', '0002_alter_allproduct_category_alter_allproduct_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allproduct',
            old_name='category',
            new_name='product_category',
        ),
        migrations.RenameField(
            model_name='allproduct',
            old_name='desc',
            new_name='product_desc',
        ),
        migrations.RenameField(
            model_name='allproduct',
            old_name='price',
            new_name='product_price',
        ),
    ]
