# Generated by Django 5.1.3 on 2024-11-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiView', '0003_rename_category_allproduct_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproduct',
            name='product_isInCart',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='allproduct',
            name='product_img',
            field=models.ImageField(blank=True, default='/media/default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='allproduct',
            name='product_price',
            field=models.FloatField(default=0),
        ),
    ]
