# Generated by Django 5.1.3 on 2024-11-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiView', '0004_allproduct_product_isincart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproduct',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
