# Generated by Django 5.1.3 on 2024-11-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiView', '0005_allproduct_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproduct',
            name='product_quantity',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
