# Generated by Django 5.1.3 on 2024-11-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiView', '0006_alter_allproduct_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allproduct',
            old_name='product_quantity',
            new_name='product_cartQuantity',
        ),
    ]
